import { createClient } from '@libsql/client';
import { readFileSync } from 'fs';
const env = readFileSync('.env.local', 'utf-8');
const parsed = Object.fromEntries(env.split('\n').filter(l => l.includes('=')).map(l => { const i = l.indexOf('='); return [l.slice(0, i), l.slice(i+1).replace(/^"(.*)"$/, '$1')]; }));
const db = createClient({ url: parsed.TURSO_DATABASE_URL, authToken: parsed.TURSO_AUTH_TOKEN });
const latest = (await db.execute({ sql: `SELECT id, version FROM akb_versions ORDER BY id DESC LIMIT 1`, args: [] })).rows[0];
const old = (await db.execute({ sql: `SELECT akb_version_id FROM runs WHERE id = 2`, args: [] })).rows[0];
console.log(`Run 2 currently linked to akb_version_id=${old.akb_version_id}; updating to ${latest.id} (v${latest.version}).`);
await db.execute({ sql: `UPDATE runs SET akb_version_id = ? WHERE id = ?`, args: [latest.id, 2] });
console.log('Done.');
